upstream blue {
    server blue-app:3002;
}

upstream green {
    server green-app:3002;
}

server {
    listen 80;

    location / {
        proxy_pass http://blue; # switch to green when deploying new version
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}