events {}

http {

    upstream myapp {
         server blue-app:80;
       # server green-app:80;
    }

    server {
        listen 80;
        server_name _;

        location / {
            proxy_pass http://myapp;
        }
    }
}
