events {}

http {
  upstream blue {
      server blue-app:3002;
  }

  upstream green {
      server green-app:3002;
  }

  server {
      listen 80;

      # Serve React frontend build
      root /app/frontend/build;
      index index.html;

      location / {
          try_files $uri /index.html;
      }

      # Proxy API requests to backend
      location /api/ {
          proxy_pass http://blue;   # switch to green during deploy
          proxy_http_version 1.1;
          proxy_set_header Upgrade $http_upgrade;
          proxy_set_header Connection 'upgrade';
          proxy_set_header Host $host;
          proxy_cache_bypass $http_upgrade;
      }
  }
}
